version: 2
build:
  image: latest
submodules:
  include: all
python:
  version: 3
  install:
    - method: pip
      path: .
    - requirements: doc/requirements.txt
  system_packages: true
formats:
  - htmlzip
