name: Build docs and check links
on: [push, pull_request]
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Double-check Python version
      run: |
        python --version
    - name: Install Python package
      run: |
        python -m pip install .
    - name: Install docs dependencies
      run: |
        python -m pip install -r doc/requirements.txt
    - name: Build HTML
      run: |
        python -m sphinx doc/ _build/html/ -d _doctrees/ -W -b html
    - name: Check links
      run: |
        python -m sphinx doc/ _build/linkcheck/ -d _doctrees/ -W -b linkcheck
