name: Build docs and check links
on: [push, pull_request]
env:
  PYTHONWARNINGS: error
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Double-check Python version
      run: |
        python --version
    - name: Install Python package
      run: |
        python -m pip install .
    - name: Install docs dependencies
      run: |
        python -m pip install -r doc/requirements.txt
    - name: Build HTML
      env:
        # sphinxcontrib-htmlhelp creates deprecation warnings: https://github.com/sphinx-doc/sphinx/issues/11127
        PYTHONWARNINGS: error,ignore::PendingDeprecationWarning
      run: |
        python -m sphinx -W --keep-going --color -d _build/doctrees/ doc/ _build/html/ -b html
    - name: Upload error log
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: build-log
        path: /tmp/sphinx-err-*.log
    - name: Check links
      env:
        # See above
        PYTHONWARNINGS: error,ignore::PendingDeprecationWarning
      run: |
        python -m sphinx -W --keep-going --color -d _build/doctrees/ doc/ _build/linkcheck/ -b linkcheck
    - name: Upload linkcheck results
      uses: actions/upload-artifact@v3
      if: ${{ success() || failure() }}
      with:
        name: linkcheck
        path: _build/linkcheck/output.*
